version: '3'
services:
   queue:
     container_name: activemq-broker
     image: skp/activemq:5.15
     build:
       context: ./ActiveMQContainer
       dockerfile: ./ActiveMQContainer/Dockerfile
     restart: on-failure
     ports:
       - "8161:8161"
       - "61616:61616"
   backend:
     container_name: usrmgmtsrvc
     image: skp/usrmgmtsrvc:1.0
     build:
       context: ./
       dockerfile: Dockerfile
     volumes:
       - /data/usermgmtsrvc
     restart: on-failure
     ports:
       - "8080:8080"
     depends_on:
       - queue